### ISSUE TITLE
"Bayesian Estimation Supersedes the t-Test" broken link

### ISSUE THREAD

**Issue by jerome-white** [ericmjl/bayesian-analysis-recipes#11]
The link for _Bayesian Estimation Supersedes the t-Test_ ([here](https://kruschke.sitehost.iu.edu/BEST/BEST.pdf)) is broken. Perhaps better to use the [DOI](https://doi.org/10.1037/a0029146)?

**Comment by ericmjl** [comment]
Wonderful catch, thank you @jerome-white!

**Comment by jerome-white** [comment]
Thanks for addressing this so quickly! To reflect the URL change on the website, does `bayesian-analysis-recipes/docs/index.md` need to be updated as well?
