### ISSUE TITLE
Hello I have a one question in "bayesian-stats-talk"

### ISSUE THREAD

**Issue by sungreong** [ericmjl/bayesian-analysis-recipes#2]
thanks you for good open sources 
https://ericmjl.github.io/bayesian-stats-talk/
it is good code , but I want to see "the problem type 3: complicated stuff example: bayesian neural networks "

but it is closed. so can you give me the new Forest Cover Notebook ??

**Comment by ericmjl** [comment]
Hello @sungreong, the Bayesian stats talk repository is here: https://github.com/ericmjl/bayesian-deep-learning-demystified, and it is not the current repository we are discussing this issue on. Hope this helps!
